// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"AW","regions":[{"code":"X01~","name":"Aruba","lon":-69.99,"lat":12.54,"b":[-70.06,12.42,-69.89,12.63],"d":["ptLsmAOLETb@W?QKJ"]}]} as const;
