// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"BL","regions":[{"code":"X00~","name":"Saint Barthélemy","lon":-62.83,"lat":17.9,"b":[-62.87,17.88,-62.79,17.93],"d":["xgKwnBFIOBJH"]}]} as const;
