// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"CW","regions":[{"code":"X01~","name":"Curaçao","lon":-68.93,"lat":12.18,"b":[-69.17,12.04,-68.74,12.39],"d":["|lLsjAGJNBb@Od@a@BSSJMX_@JKN"]}]} as const;
