// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"EH","regions":[{"code":"X01~","name":"Western Sahara","lon":-12.39,"lat":24.54,"b":[-17.1,20.77,-8.68,27.66],"d":["xw@ihDy@EGEJ_@E]Jg@[?BlIzSB?zNbA\\v@JpAr@Zh@?ZKf@MjFtW?XvACZHQQoBw@IiCEuELYAQIOSK]DUqAyAW}CO}@Yw@WS{Ae@q@sAMMoBgAWw@q@oDEG}@MGUa@s@a@_@CUN[}AY_@Ai@F{@Zk@IYLO?QA_Am@aA?"]}]} as const;
