// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"GG","regions":[{"code":"X01~","name":"Sark","lon":-2.58,"lat":49.47,"b":[-2.67,49.43,-2.5,49.51],"d":["dOitHOCHPZ?QK"]}]} as const;
