// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"GU","regions":[{"code":"X01~","name":"Guam","lon":144.77,"lat":13.46,"b":[144.62,13.25,144.95,13.64],"d":["qh[gtAKJb@b@Hb@L?JSCIFE_@QKUIA"]}]} as const;
