// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"HM","regions":[{"code":"X01~","name":"Heard Island and McDonald Islands","lon":73.48,"lat":-53.06,"b":[73.24,-53.19,73.81,-52.96],"d":["{kM~jIMBh@L\\BNIHSVCBGKCOLCEEHYAc@R"]}]} as const;
