// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"IM","regions":[{"code":"X01~","name":"Isle of Man","lon":-4.53,"lat":54.22,"b":[-4.79,54.06,-4.31,54.41],"d":["z[{pIRCRDO_@SIUW]CFLMLRNAFl@Z"]}]} as const;
