// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"IO","regions":[{"code":"X01~","name":"British Indian Ocean Territory","lon":72.43,"lat":-7.36,"b":[72.36,-7.43,72.47,-7.27],"d":["}cMdm@HJ?UNIMJ?VGI"]}]} as const;
