// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"JE","regions":[{"code":"X01~","name":"Jersey","lon":-2.12,"lat":49.22,"b":[-2.24,49.17,-2.02,49.26],"d":["`L{rHKD?NXGFFL?BO_@?"]}]} as const;
