// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"KI","regions":[{"code":"X01~","name":"Kiribati","lon":-157.4,"lat":1.88,"b":[-159.41,-11.46,175.06,3.93],"d":["zs\\ffAELDBBM","zg]jXMCBLLG","cea@`H?RJDAIECDLEEDMC?","ica@pFALD?HYIN","nu]_JAHNB`A]BIKCDLUFJGECGHBMEAAHCI^MQ?UJHV_@T","pb^eWEJLHJGMB?ELMHDCJHCEMSL","az`@uKDABHCKCTHAI?DK"]}]} as const;
