// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"KY","regions":[{"code":"X01~","name":"Cayman Islands","lon":-81.27,"lat":19.34,"b":[-81.42,19.26,-79.73,19.76],"d":["dzN}wBIBDHx@H?OFEGCEROEDG]D","hsNczBO?^HMG","frNczBWKCD\\H"]}]} as const;
