// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"MC","regions":[{"code":"X01~","name":"Monaco","lon":7.4,"lat":43.75,"b":[7.37,43.72,7.44,43.76],"d":["im@opGEDNDGG"]}]} as const;
