// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"MF","regions":[{"code":"X00~","name":"St. Martin","lon":-63.05,"lat":18.06,"b":[-63.15,18.03,-63.02,18.12],"d":["|hKuoBZGYI?R"]}]} as const;
