// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"MH","regions":[{"code":"L","name":"Railik Chain","lon":169.64,"lat":5.88,"b":[169.59,5.8,169.73,6.01],"d":["}b`@gc@M[MMLNJ\\F?"]},{"code":"T","name":"Ratak Chain","lon":171.68,"lat":7.0,"b":[171.04,6.97,171.76,7.17],"d":["op`@qj@^GFGc@P","en`@mk@^Hh@QAAAFa@L_@E"]}]} as const;
