// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"MO","regions":[{"code":"M","name":"Macau","lon":113.56,"lat":22.14,"b":[113.53,22.11,113.59,22.16],"d":["wdUoiCEHHBDGEA"]}]} as const;
