// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"MS","regions":[{"code":"P","name":"Saint Peter","lon":-62.2,"lat":16.77,"b":[-62.23,16.74,-62.17,16.82],"d":["~cKugBEMEBDNHA"]},{"code":"A","name":"Saint Anthony","lon":-62.19,"lat":16.71,"b":[-62.23,16.68,-62.15,16.75],"d":["ncKogBDHJABG?COF"]}]} as const;
