// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"MV","regions":[{"code":"12","name":"Malé","lon":73.51,"lat":4.2,"b":[73.43,4.16,73.55,4.24],"d":["ujMoYHPPCOAGI"]}]} as const;
