// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"NF","regions":[{"code":"X01~","name":"Norfolk Island","lon":167.96,"lat":-29.04,"b":[167.93,-29.08,167.98,-29.0],"d":["{x_@ltDBLHA?MID"]}]} as const;
