// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"NU","regions":[{"code":"X01~","name":"Niue","lon":-169.87,"lat":-19.03,"b":[-169.93,-19.13,-169.78,-18.97],"d":["rd`@ruBC?ITRLL??WEGI?"]}]} as const;
