// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"PM","regions":[{"code":"X01~","name":"Saint-Pierre","lon":-56.18,"lat":46.78,"b":[-56.24,46.76,-56.15,46.81],"d":["~}ImcHDFNAIGGD"]},{"code":"X02~","name":"Miquelon-Langlade","lon":-56.32,"lat":46.98,"b":[-56.4,46.78,-56.24,47.14],"d":["v~IcdHEFBFTLJKMML[BKEEE?FDAFUHFLN?GD?NG?"]}]} as const;
