// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"PN","regions":[{"code":"X01~","name":"Pitcairn Islands","lon":-128.32,"lat":-24.36,"b":[-128.34,-24.41,-128.29,-24.32],"d":["baX`wCGJBHHGAI"]}]} as const;
