// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"PR","regions":[{"code":"PR","name":"Puerto Rico","lon":-66.44,"lat":18.18,"b":[-67.94,17.92,-65.25,18.52],"d":["dgLepBBLNGOC","nwKepBZDR?BEc@IUDLH","`wKgqBJKMDADHAAF","fyKgqBELFABFTDTXAFVLt@JBGj@BJG^F^GJHVF\\GHDNC?FFIIEHEI]X_@UKBMMEe@FiB?o@DEJICLEm@De@POCBV"]}]} as const;
