// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"ST","regions":[{"code":"S","name":"São Tomé","lon":6.63,"lat":0.27,"b":[6.47,0.02,6.76,0.41],"d":["wh@qAMNART\\ZRLq@KO]K"]},{"code":"P","name":"Príncipe","lon":7.41,"lat":1.63,"b":[7.33,1.53,7.46,1.69],"d":["sm@mIFDEDLTNG?GKOMD"]}]} as const;
