// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"SX","regions":[{"code":"SX","name":"Sint Maarten","lon":-63.08,"lat":18.05,"b":[-63.11,18.03,-63.02,18.06],"d":["niK{oBQFPABC"]}]} as const;
