// Generated by scripts/admin1.py from Natural Earth 10m admin-1. Do not edit.
export default {"cc":"VG","regions":[{"code":"X01~","name":"British Virgin Islands","lon":-64.63,"lat":18.42,"b":[-64.71,18.39,-64.27,18.75],"d":["`sKarBNDMKWBXF","lqKorBLHCMQ?JF","dqK_tBNCQAIJNC"]}]} as const;
