#!/usr/bin/env python3
"""Rasterises Natural Earth land (topojson 50m) into a 0.5° land mask for the dot-matrix map.
Output: app/ui/app/data/landMask.ts, one bit per cell, rows north→south, base64."""
import json, base64, pathlib
import numpy as np
ROOT = pathlib.Path(__file__).resolve().parent.parent
topo = json.load(open(ROOT / "data/geo/countries-50m.json"))
sx, sy = topo["transform"]["scale"]; tx, ty = topo["transform"]["translate"]
arcs = []
for a in topo["arcs"]:
    x = y = 0; pts = []
    for dx, dy in a:
        x += dx; y += dy; pts.append((x * sx + tx, y * sy + ty))
    arcs.append(pts)
def ring(idx):
    out = []
    for i in idx:
        pts = arcs[i] if i >= 0 else arcs[~i][::-1]
        out.extend(pts if not out else pts[1:])
    return np.array(out)
geoms = topo["objects"]["land"]["geometries"]
polys = []
for g in geoms:
    if g["type"] == "Polygon": polys.append([ring(r) for r in g["arcs"]])
    elif g["type"] == "MultiPolygon": polys.extend([[ring(r) for r in p] for p in g["arcs"]])
STEP = 0.5
FINE = STEP / 2  # sample at 0.25° and keep a cell as land when any sub-cell is land, so coastal sites sit on land
lons = np.arange(-180 + FINE / 2, 180, FINE); lats = np.arange(90 - FINE / 2, -90, -FINE)
LON, LAT = np.meshgrid(lons, lats)
mask = np.zeros(LON.shape, dtype=bool)
for rings in polys:
    x0, y0 = rings[0].min(axis=0); x1, y1 = rings[0].max(axis=0)
    sel = (LON >= x0) & (LON <= x1) & (LAT >= y0) & (LAT <= y1)
    if not sel.any(): continue
    px, py = LON[sel], LAT[sel]; inside = np.zeros(px.shape, dtype=bool)
    for r in rings:
        xa, ya = r[:-1, 0], r[:-1, 1]; xb, yb = r[1:, 0], r[1:, 1]
        for k in range(0, len(xa), 400):
            A, B, C, D = xa[k:k+400, None], ya[k:k+400, None], xb[k:k+400, None], yb[k:k+400, None]
            cond = ((B > py) != (D > py)) & (px < (C - A) * (py - B) / np.where(D - B == 0, 1e-12, D - B) + A)
            inside ^= (np.count_nonzero(cond, axis=0) % 2).astype(bool)
    mask[sel] |= inside
mask = mask.reshape(mask.shape[0] // 2, 2, mask.shape[1] // 2, 2).any(axis=(1, 3))
bits = np.packbits(mask.flatten())
b64 = base64.b64encode(bits.tobytes()).decode()
out = ROOT / "app/ui/app/data/landMask.ts"
out.write_text(f"""// Generated by scripts/land_mask.py from Natural Earth 50m land. Do not edit.
// {mask.shape[1]}×{mask.shape[0]} cells of {STEP}°, rows from 90°N southwards, one bit per cell (1 = land).
export const LAND_STEP = {STEP};
export const LAND_COLS = {mask.shape[1]};
export const LAND_ROWS = {mask.shape[0]};
export const LAND_BITS = "{b64}";
""")
print("land cells", int(mask.sum()), "of", mask.size, "·", len(b64), "chars")
